name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version from tag
        id: tag_name
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Extract Changelog
        uses: mindsers/changelog-reader-action@v2
        id: changelog_reader
        with:
          version: ${{ steps.tag_name.outputs.version }}
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build and publish to Curseforge & Modrinth
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: curseforge modrinth --stacktrace
        env:
          CURSE_API_KEY: ${{ secrets.CF_API_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ steps.changelog_reader.outputs.changes }}
      - name: Publish to Github releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
